In [7]:
import pandas as pd
import numpy as np
import scipy as sp

In [90]:
# import sys
# !{sys.executable} -m pip install BayesPy

In [91]:
import seaborn as sns
from matplotlib import pyplot as plt

In [475]:
import numpy as np

class UGMM(object):
    
    def __init__(self, X, K=1):
        self.X = X
        self.K = K
        self.N = self.X.shape[0]

    def _init(self):
        self.alpha=np.random.rand(self.K,1)
        self.m= np.random.rand(self.K,1)
        self.beta=np.random.rand(self.K,1)
        self.beta_prev=np.random.rand(self.K,1)
        self.nu=np.random.rand(self.K,1)*np.random.randint(1,10)
        self.W=np.random.rand(self.K,1)*np.random.randint(1,10)
        self.alpha=np.random.rand(self.K,1)
        self.r=np.zeros((self.N,self.K))
        self.x_nebla=np.zeros((self.K,1))
        self.Nk=np.zeros((self.K,1))
        self.S=np.zeros((self.K,1))
        self.pi_nebla=np.zeros((self.K,1))
        self.lamda_nebla=np.zeros((self.K,1))
        self.E_mu_lamda=np.zeros((self.N,self.K))
        
        

        print('Init mean')
        print(self.m)
        print('Init lamda')


    def E_Step(self):
        for n in range(self.N):
            for k in range(self.K):
                self.pi_nebla[k]=np.exp(sp.special.digamma(self.alpha[k])-sp.special.digamma(self.alpha.sum()))
                self.lamda_nebla[k]=np.exp(sp.special.digamma(self.nu[k]/2, out=None)+np.log(2)+np.log(self.W[k]))
                self.E_mu_lamda[n][k]=(self.beta[k]**(-1))+self.nu[k]*self.W[k]*(self.X[n]-self.m[k])**2
                self.r[n][k]=self.pi_nebla[k]*(self.lamda_nebla[k]**0.5)*(np.exp(-0.5*self.E_mu_lamda[n][k]))
        row_sums = self.r.sum(axis=1)
        self.r= self.r / row_sums[:, np.newaxis]
        
        
    def fit(self, max_iter=1000, tol=1e-6):
        self._init()
#         self.r_values = [self.r_elbo()]
        self.m_history = [self.m.copy()]
        self.E_Step()
#         self.s2_history = [self.s2]
        for iter_ in range(1, max_iter+1):
#             print('before')
#             print(self.m_history)
            self.M_Step()
#             print('after')
#             print(self.m_history)
            self.m_history.append(self.m.copy())
#             if iter_ % 2 == 0:
#             print('wow')
            print(iter_, self.m_history[iter_])
            print(iter_, self.r)
            if np.linalg.norm(self.m_history[-1]-self.m_history[-2],2) <= tol:
                print('ELBO converged with ll %.3f at iteration %d'%(self.m_history[-1][0],iter_))
                break
            self.E_Step()
        if iter_ == max_iter:
            print('ELBO ended with ll %.3f'%(self.m_history[-1][0]))


    def M_Step(self):
        self._update_Nk()
        self._update_x_nebla()
        self._update_S()
        self._update_alpha()
        self._update_W()
        self._update_beta()
        self._update_nu()
        self._update_m()

    def _update_Nk(self):
        for k in range(self.K):
            self.Nk[k]=self.r[:,k].sum()
            
    def _update_x_nebla(self):
        for k in range(self.K):
            self.x_nebla[k]=0
            for n in range(self.N):
#                 print(self.Nk)
                self.x_nebla[k]+=self.r[n][k]*self.X[n]/self.Nk[k]
    
    def _update_S(self):
        for k in range(self.K):
            self.S[k]=0
            for n in range(self.N):
                self.S[k]+=(self.r[n][k]*(self.X[n]-self.x_nebla[k])**(2))/self.Nk[k]
                
    def _update_alpha(self):
        for k in range(self.K):
            self.alpha[k]=self.alpha[k]+self.Nk[k]
            
    def _update_beta(self):
        self.beta_prev=self.beta.copy()
        for k in range(self.K):
            self.beta[k]=self.beta[k]+self.Nk[k]
        
    def _update_m(self):
        for k in range(self.K):
            self.m[k]=(self.beta_prev[k]*self.m[k]+self.Nk[k]*self.x_nebla[k])/self.beta[k]
#         print('achha')
#         print(self.m)
    
    
    def _update_W(self):
        for k in range(self.K):
            self.W[k]=((1/self.W[k])+self.Nk[k]*self.S[k]+(self.beta[k]*self.Nk[k]/(self.beta[k]+self.Nk[k]))*(self.x_nebla[k]-self.m[k])**2)**(-1)
        
    
    def _update_nu(self):
        for k in range(self.K):
            self.nu[k]=self.nu[k]+self.Nk[k]
    
#     def _calculate_rnk
        

In [476]:
data=pd.read_csv('data2.txt',header=None)

In [477]:
X =np.array(data.iloc[0,0])
for i in range(1,1000):
    X= np.append(X, data.iloc[i,0])
    

In [478]:
X.max()

0.9942949885119834

In [480]:
ugmm = UGMM(X, 3)
ugmm.fit()

Init mean
[[0.83346122]
 [0.54705876]
 [0.63144309]]
Init lamda
1 [[0.62031465]
 [0.45238812]
 [0.44555295]]
1 [[1.17185078e-04 9.79736548e-01 2.01462671e-02]
 [8.67458680e-05 9.78643912e-01 2.12693425e-02]
 [7.98104420e-05 9.78231894e-01 2.16882951e-02]
 ...
 [1.63598168e-04 9.79962219e-01 1.98741829e-02]
 [2.07435945e-04 9.78793656e-01 2.09989079e-02]
 [1.31386072e-04 9.79959680e-01 1.99089343e-02]]
2 [[0.61974716]
 [0.45210543]
 [0.46021921]]
2 [[7.43771069e-07 9.96013956e-01 3.98530069e-03]
 [7.90433942e-07 9.94933004e-01 5.06620566e-03]
 [8.46093891e-07 9.94261752e-01 5.73740162e-03]
 ...
 [1.18312820e-06 9.94425387e-01 5.57343032e-03]
 [3.42433332e-06 9.83776696e-01 1.62198797e-02]
 [8.03457276e-07 9.95924207e-01 4.07498957e-03]]
3 [[0.61947484]
 [0.45202521]
 [0.46824928]]
3 [[3.79760446e-07 9.96871428e-01 3.12819227e-03]
 [4.05361955e-07 9.96028906e-01 3.97068892e-03]
 [4.34987641e-07 9.95501851e-01 4.49771449e-03]
 ...
 [6.08990161e-07 9.95589743e-01 4.40964796e-03]
 [1.806810

26 [[0.61826892]
 [0.45196868]
 [0.49928426]]
26 [[3.34632483e-08 9.98088580e-01 1.91138635e-03]
 [3.58759646e-08 9.97689742e-01 2.31022210e-03]
 [3.85813622e-08 9.97430267e-01 2.56969444e-03]
 ...
 [5.39026718e-08 9.97289652e-01 2.71029397e-03]
 [1.62873451e-07 9.92463163e-01 7.53667449e-03]
 [3.61796884e-08 9.98023485e-01 1.97647928e-03]]
27 [[0.61824924]
 [0.45196946]
 [0.49961182]]
27 [[3.22292775e-08 9.98092175e-01 1.90779250e-03]
 [3.45537875e-08 9.97697422e-01 2.30254386e-03]
 [3.71597218e-08 9.97440230e-01 2.55973281e-03]
 ...
 [5.19136171e-08 9.97294745e-01 2.70520302e-03]
 [1.56862491e-07 9.92493923e-01 7.50592056e-03]
 [3.48452441e-08 9.98026713e-01 1.97325219e-03]]
28 [[0.61823028]
 [0.45197023]
 [0.49992006]]
28 [[3.10849528e-08 9.98095339e-01 1.90463015e-03]
 [3.33276243e-08 9.97704492e-01 2.29547461e-03]
 [3.58413017e-08 9.97449476e-01 2.55048808e-03]
 ...
 [5.00690744e-08 9.97299231e-01 2.70071850e-03]
 [1.51287907e-07 9.92522583e-01 7.47726607e-03]
 [3.36077534e-08 9.9

50 [[0.6179298 ]
 [0.45198295]
 [0.50387657]]
50 [[1.75699908e-08 9.98110931e-01 1.88905153e-03]
 [1.88430299e-08 9.97780258e-01 2.21972323e-03]
 [2.02656950e-08 9.97557603e-01 2.44237708e-03]
 ...
 [2.82865121e-08 9.97322219e-01 2.67775244e-03]
 [8.54395440e-08 9.92873393e-01 7.12652120e-03]
 [1.89932803e-08 9.98037268e-01 1.96271266e-03]]
51 [[0.61791958]
 [0.45198339]
 [0.50398093]]
51 [[1.72336497e-08 9.98110457e-01 1.88952607e-03]
 [1.84824801e-08 9.97781816e-01 2.21816571e-03]
 [1.98779605e-08 9.97560215e-01 2.43976508e-03]
 ...
 [2.77445173e-08 9.97321613e-01 2.67835902e-03]
 [8.38009324e-08 9.92882557e-01 7.11735925e-03]
 [1.86296020e-08 9.98036465e-01 1.96351671e-03]]
52 [[0.61790956]
 [0.45198382]
 [0.50408137]]
52 [[1.69102305e-08 9.98109936e-01 1.89004710e-03]
 [1.81357783e-08 9.97783289e-01 2.21669317e-03]
 [1.95051169e-08 9.97562720e-01 2.43726041e-03]
 ...
 [2.72233526e-08 9.97320943e-01 2.67902990e-03]
 [8.22253018e-08 9.92891402e-01 7.10851535e-03]
 [1.82798975e-08 9.9

74 [[0.61772783]
 [0.45199144]
 [0.50559318]]
74 [[1.20003344e-08 9.98091760e-01 1.90822822e-03]
 [1.28719260e-08 9.97801686e-01 2.19830144e-03]
 [1.38442142e-08 9.97599652e-01 2.40033447e-03]
 ...
 [1.93124991e-08 9.97296975e-01 2.70300559e-03]
 [5.83101597e-08 9.93031789e-01 6.96815257e-03]
 [1.29711755e-08 9.98010891e-01 1.98909605e-03]]
75 [[0.61772092]
 [0.45199172]
 [0.50563945]]
75 [[1.18452498e-08 9.98090774e-01 1.90921447e-03]
 [1.27056451e-08 9.97802110e-01 2.19787763e-03]
 [1.36653863e-08 9.97600776e-01 2.39921053e-03]
 ...
 [1.90626654e-08 9.97295670e-01 2.70431130e-03]
 [5.75549765e-08 9.93036501e-01 6.96344147e-03]
 [1.28035013e-08 9.98009634e-01 1.99035301e-03]]
76 [[0.61771411]
 [0.451992  ]
 [0.50568435]]
76 [[1.16942148e-08 9.98089782e-01 1.91020666e-03]
 [1.25437051e-08 9.97802511e-01 2.19747679e-03]
 [1.34912265e-08 9.97601867e-01 2.39811902e-03]
 ...
 [1.88193580e-08 9.97294356e-01 2.70562472e-03]
 [5.68195281e-08 9.93041114e-01 6.95882929e-03]
 [1.26402058e-08 9.9

99 [[0.6175782 ]
 [0.45199742]
 [0.50642661]]
99 [[9.05613205e-09 9.98066353e-01 1.93363767e-03]
 [9.71497522e-09 9.97807259e-01 2.19273134e-03]
 [1.04490026e-08 9.97620384e-01 2.37960542e-03]
 ...
 [1.45700883e-08 9.97263435e-01 2.73655017e-03]
 [4.39766305e-08 9.93126814e-01 6.87314243e-03]
 [9.78806773e-09 9.97979305e-01 2.02068496e-03]]
100 [[0.61757304]
 [0.45199762]
 [0.50644929]]
100 [[8.96870238e-09 9.98065338e-01 1.93465299e-03]
 [9.62122132e-09 9.97807329e-01 2.19266093e-03]
 [1.03481714e-08 9.97620978e-01 2.37901179e-03]
 ...
 [1.44292801e-08 9.97262101e-01 2.73788501e-03]
 [4.35511111e-08 9.93129874e-01 6.87008273e-03]
 [9.69354729e-09 9.97978066e-01 2.02192444e-03]]
101 [[0.61756792]
 [0.45199782]
 [0.50647136]]
101 [[8.88298433e-09 9.98064325e-01 1.93566639e-03]
 [9.52930245e-09 9.97807392e-01 2.19259832e-03]
 [1.02493136e-08 9.97621559e-01 2.37843116e-03]
 ...
 [1.42912299e-08 9.97260769e-01 2.73921684e-03]
 [4.31339303e-08 9.93132892e-01 6.86706495e-03]
 [9.60087752e-09

123 [[0.61746669]
 [0.45200166]
 [0.50683313]]
123 [[7.34605447e-09 9.98042696e-01 1.95729646e-03]
 [7.88112251e-09 9.97807295e-01 2.19269675e-03]
 [8.47669878e-09 9.97631726e-01 2.36826571e-03]
 ...
 [1.18162184e-08 9.97232470e-01 2.76751810e-03]
 [3.56553543e-08 9.93190698e-01 6.80926667e-03]
 [7.93934440e-09 9.97950669e-01 2.04932304e-03]]
124 [[0.61746253]
 [0.45200182]
 [0.50684504]]
124 [[7.28899629e-09 9.98041749e-01 1.95824409e-03]
 [7.81993155e-09 9.97807241e-01 2.19275075e-03]
 [8.41088745e-09 9.97632094e-01 2.36789777e-03]
 ...
 [1.17243435e-08 9.97231236e-01 2.76875228e-03]
 [3.53777742e-08 9.93193007e-01 6.80695744e-03]
 [7.87766197e-09 9.97949531e-01 2.05046160e-03]]
125 [[0.6174584 ]
 [0.45200197]
 [0.50685664]]
125 [[7.23283872e-09 9.98040804e-01 1.95918835e-03]
 [7.75970624e-09 9.97807184e-01 2.19280788e-03]
 [8.34611464e-09 9.97632455e-01 2.36753634e-03]
 ...
 [1.16339195e-08 9.97230007e-01 2.76998157e-03]
 [3.51045802e-08 9.93195294e-01 6.80467084e-03]
 [7.81695327e-

148 [[0.61737164]
 [0.45200513]
 [0.50705131]]
148 [[6.14803286e-09 9.98020038e-01 1.97995585e-03]
 [6.59628349e-09 9.97805224e-01 2.19476967e-03]
 [7.09483639e-09 9.97639298e-01 2.36069451e-03]
 ...
 [9.88733264e-09 9.97203100e-01 2.79689047e-03]
 [2.98282169e-08 9.93242626e-01 6.75734455e-03]
 [6.64425784e-09 9.97923569e-01 2.07642478e-03]]
149 [[0.61736818]
 [0.45200526]
 [0.50705719]]
149 [[6.10836009e-09 9.98019176e-01 1.98081741e-03]
 [6.55373411e-09 9.97805118e-01 2.19487569e-03]
 [7.04907362e-09 9.97639543e-01 2.36044949e-03]
 ...
 [9.82346342e-09 9.97201989e-01 2.79800144e-03]
 [2.96352913e-08 9.93244490e-01 6.75548078e-03]
 [6.60137181e-09 9.97922542e-01 2.07745090e-03]]
150 [[0.61736475]
 [0.45200538]
 [0.50706291]]
150 [[6.06920836e-09 9.98018318e-01 1.98167557e-03]
 [6.51174344e-09 9.97805011e-01 2.19498293e-03]
 [7.00391173e-09 9.97639785e-01 2.36020807e-03]
 ...
 [9.76043345e-09 9.97200883e-01 2.79910758e-03]
 [2.94449023e-08 9.93246340e-01 6.75363076e-03]
 [6.55904908e-

172 [[0.61729442]
 [0.45200785]
 [0.50715083]]
172 [[5.32142691e-09 9.98000276e-01 1.99971864e-03]
 [5.70971802e-09 9.97802419e-01 2.19757510e-03]
 [6.14131202e-09 9.97644325e-01 2.35566865e-03]
 ...
 [8.55667333e-09 9.97177728e-01 2.82226314e-03]
 [2.58091240e-08 9.93283991e-01 6.71598362e-03]
 [5.75071740e-09 9.97900094e-01 2.09990062e-03]]
173 [[0.61729144]
 [0.45200795]
 [0.50715337]]
173 [[5.29188778e-09 9.97999493e-01 2.00050202e-03]
 [5.67803526e-09 9.97802294e-01 2.19770053e-03]
 [6.10723621e-09 9.97644502e-01 2.35549217e-03]
 ...
 [8.50912549e-09 9.97176727e-01 2.82326405e-03]
 [2.56655258e-08 9.93285580e-01 6.71439462e-03]
 [5.71878698e-09 9.97899165e-01 2.10082879e-03]]
174 [[0.61728848]
 [0.45200805]
 [0.50715581]]
174 [[5.26268272e-09 9.97998712e-01 2.00128232e-03]
 [5.64671075e-09 9.97802168e-01 2.19782642e-03]
 [6.07354571e-09 9.97644676e-01 2.35531790e-03]
 ...
 [8.46211568e-09 9.97175731e-01 2.82426066e-03]
 [2.55235535e-08 9.93287159e-01 6.71281502e-03]
 [5.68721772e-

197 [[0.61722466]
 [0.45201022]
 [0.50718692]]
197 [[4.67156353e-09 9.97981579e-01 2.01841626e-03]
 [5.01267823e-09 9.97799190e-01 2.20080463e-03]
 [5.39162097e-09 9.97648158e-01 2.35183648e-03]
 ...
 [7.51068489e-09 9.97153943e-01 2.84604994e-03]
 [2.26504086e-08 9.93321173e-01 6.67880484e-03]
 [5.04825676e-09 9.97877982e-01 2.12201297e-03]]
198 [[0.61722205]
 [0.4520103 ]
 [0.50718735]]
198 [[4.64892816e-09 9.97980868e-01 2.01912745e-03]
 [4.98839902e-09 9.97799059e-01 2.20093622e-03]
 [5.36550772e-09 9.97648290e-01 2.35170492e-03]
 ...
 [7.47425479e-09 9.97153042e-01 2.84695043e-03]
 [2.25404057e-08 9.93322561e-01 6.67741671e-03]
 [5.02378983e-09 9.97877142e-01 2.12285249e-03]]
199 [[0.61721946]
 [0.45201039]
 [0.50718771]]
199 [[4.62651644e-09 9.97980159e-01 2.01983596e-03]
 [4.96435966e-09 9.97798927e-01 2.20106789e-03]
 [5.33965241e-09 9.97648420e-01 2.35157478e-03]
 ...
 [7.43818483e-09 9.97152145e-01 2.84784721e-03]
 [2.24314909e-08 9.93323942e-01 6.67603538e-03]
 [4.99956467e-

221 [[0.61716552]
 [0.45201217]
 [0.50718134]]
221 [[4.18395004e-09 9.97965221e-01 2.03477500e-03]
 [4.48964277e-09 9.97796029e-01 2.20396605e-03]
 [4.82907380e-09 9.97650965e-01 2.34903062e-03]
 ...
 [6.72594772e-09 9.97133311e-01 2.86668244e-03]
 [2.02810095e-08 9.93352761e-01 6.64721921e-03]
 [4.52119468e-09 9.97858697e-01 2.14129841e-03]]
222 [[0.6171632 ]
 [0.45201224]
 [0.50718048]]
222 [[4.16588260e-09 9.97964570e-01 2.03542593e-03]
 [4.47026243e-09 9.97795898e-01 2.20409720e-03]
 [4.80822933e-09 9.97651067e-01 2.34892779e-03]
 ...
 [6.69687285e-09 9.97132493e-01 2.86749993e-03]
 [2.01932291e-08 9.93354005e-01 6.64597497e-03]
 [4.50166586e-09 9.97857931e-01 2.14206478e-03]]
223 [[0.61716089]
 [0.45201232]
 [0.50717959]]
223 [[4.14797436e-09 9.97963921e-01 2.03607453e-03]
 [4.45105281e-09 9.97795767e-01 2.20422826e-03]
 [4.78756849e-09 9.97651169e-01 2.34882595e-03]
 ...
 [6.66805430e-09 9.97131679e-01 2.86831422e-03]
 [2.01062230e-08 9.93355244e-01 6.64473596e-03]
 [4.48230914e-

245 [[0.61711246]
 [0.45201387]
 [0.50715065]]
245 [[3.79036129e-09 9.97950216e-01 2.04978067e-03]
 [4.06744581e-09 9.97792917e-01 2.20707851e-03]
 [4.37498013e-09 9.97653187e-01 2.34680854e-03]
 ...
 [6.09260036e-09 9.97114535e-01 2.88545866e-03]
 [1.83689798e-08 9.93381274e-01 6.61870722e-03]
 [4.09577587e-09 9.97841048e-01 2.15894754e-03]]
246 [[0.61711036]
 [0.45201394]
 [0.50714896]]
246 [[3.77559954e-09 9.97949617e-01 2.05037925e-03]
 [4.05161078e-09 9.97792790e-01 2.20720627e-03]
 [4.35794874e-09 9.97653270e-01 2.34672593e-03]
 ...
 [6.06884768e-09 9.97113789e-01 2.88620464e-03]
 [1.82972773e-08 9.93382406e-01 6.61757599e-03]
 [4.07982054e-09 9.97840345e-01 2.15965083e-03]]
247 [[0.61710827]
 [0.452014  ]
 [0.50714726]]
247 [[3.76095516e-09 9.97949020e-01 2.05097580e-03]
 [4.03590164e-09 9.97792662e-01 2.20733384e-03]
 [4.34105273e-09 9.97653352e-01 2.34664402e-03]
 ...
 [6.04528396e-09 9.97113046e-01 2.88694786e-03]
 [1.82261455e-08 9.93383533e-01 6.61644895e-03]
 [4.06399208e-

269 [[0.61706432]
 [0.45201538]
 [0.50710361]]
269 [[3.46584988e-09 9.97936387e-01 2.06360990e-03]
 [3.71933497e-09 9.97789905e-01 2.21009158e-03]
 [4.00056790e-09 9.97654992e-01 2.34500404e-03]
 ...
 [5.57046306e-09 9.97097360e-01 2.90263395e-03]
 [1.67928871e-08 9.93407335e-01 6.59264844e-03]
 [3.74502955e-09 9.97824813e-01 2.17518296e-03]]
270 [[0.61706241]
 [0.45201543]
 [0.50710139]]
270 [[3.45355825e-09 9.97935834e-01 2.06416289e-03]
 [3.70614922e-09 9.97789782e-01 2.21021458e-03]
 [3.98638587e-09 9.97655060e-01 2.34493616e-03]
 ...
 [5.55068689e-09 9.97096676e-01 2.90331815e-03]
 [1.67331958e-08 9.93408374e-01 6.59160898e-03]
 [3.73174438e-09 9.97824165e-01 2.17583162e-03]]
271 [[0.61706051]
 [0.45201549]
 [0.50709915]]
271 [[3.44135564e-09 9.97935282e-01 2.06471411e-03]
 [3.69305897e-09 9.97789659e-01 2.21033736e-03]
 [3.97230655e-09 9.97655127e-01 2.34486880e-03]
 ...
 [5.53105405e-09 9.97095995e-01 2.90399996e-03]
 [1.66739373e-08 9.93409410e-01 6.59057297e-03]
 [3.71855544e-

294 [[0.61701852]
 [0.45201678]
 [0.50704332]]
294 [[3.18320119e-09 9.97923071e-01 2.07692585e-03]
 [3.41612153e-09 9.97786896e-01 2.21310079e-03]
 [3.67444381e-09 9.97656545e-01 2.34345139e-03]
 ...
 [5.11572598e-09 9.97080941e-01 2.91905346e-03]
 [1.54204083e-08 9.93432341e-01 6.56764356e-03]
 [3.43953741e-09 9.97809205e-01 2.19079172e-03]]
295 [[0.61701677]
 [0.45201683]
 [0.50704074]]
295 [[3.17287353e-09 9.97922559e-01 2.07743741e-03]
 [3.40504228e-09 9.97786778e-01 2.21321826e-03]
 [3.66252739e-09 9.97656601e-01 2.34339497e-03]
 ...
 [5.09911123e-09 9.97080313e-01 2.91968192e-03]
 [1.53702650e-08 9.93433301e-01 6.56668345e-03]
 [3.42837521e-09 9.97808606e-01 2.19139093e-03]]
296 [[0.61701502]
 [0.45201688]
 [0.50703814]]
296 [[3.16261434e-09 9.97922049e-01 2.07794744e-03]
 [3.39403646e-09 9.97786661e-01 2.21333551e-03]
 [3.65068995e-09 9.97656657e-01 2.34333895e-03]
 ...
 [5.08260667e-09 9.97079687e-01 2.92030832e-03]
 [1.53204545e-08 9.93434258e-01 6.56572625e-03]
 [3.41728701e-

318 [[0.61697804]
 [0.45201799]
 [0.50697847]]
318 [[2.95293992e-09 9.97911203e-01 2.08879363e-03]
 [3.16909987e-09 9.97784139e-01 2.21585781e-03]
 [3.40875626e-09 9.97657798e-01 2.34219853e-03]
 ...
 [4.74530444e-09 9.97066407e-01 2.93358840e-03]
 [1.43025315e-08 9.93454622e-01 6.54536337e-03]
 [3.19067189e-09 9.97795312e-01 2.20468492e-03]]
319 [[0.61697642]
 [0.45201804]
 [0.50697566]]
319 [[2.94408359e-09 9.97910727e-01 2.08927032e-03]
 [3.15959877e-09 9.97784027e-01 2.21596987e-03]
 [3.39853720e-09 9.97657846e-01 2.34215054e-03]
 ...
 [4.73105787e-09 9.97065825e-01 2.93417026e-03]
 [1.42595398e-08 9.93455518e-01 6.54446784e-03]
 [3.18110010e-09 9.97794754e-01 2.20524263e-03]]
320 [[0.6169748 ]
 [0.45201808]
 [0.50697285]]
320 [[2.93528155e-09 9.97910251e-01 2.08974564e-03]
 [3.15015589e-09 9.97783915e-01 2.21608171e-03]
 [3.38838077e-09 9.97657894e-01 2.34210286e-03]
 ...
 [4.71689867e-09 9.97065245e-01 2.93475030e-03]
 [1.42168120e-08 9.93456411e-01 6.54357479e-03]
 [3.17158700e-

342 [[0.61694048]
 [0.45201909]
 [0.50690935]]
342 [[2.75441846e-09 9.97900125e-01 2.09987194e-03]
 [2.95612274e-09 9.97781511e-01 2.21848606e-03]
 [3.17968497e-09 9.97658871e-01 2.34112607e-03]
 ...
 [4.42596803e-09 9.97052924e-01 2.94707161e-03]
 [1.33389174e-08 9.93475459e-01 6.52452774e-03]
 [2.97611477e-09 9.97782357e-01 2.21763979e-03]]
343 [[0.61693897]
 [0.45201913]
 [0.50690641]]
343 [[2.74673821e-09 9.97899679e-01 2.10031777e-03]
 [2.94788313e-09 9.97781404e-01 2.21859283e-03]
 [3.17082270e-09 9.97658912e-01 2.34108471e-03]
 ...
 [4.41361427e-09 9.97052383e-01 2.94761250e-03]
 [1.33016411e-08 9.93476299e-01 6.52368800e-03]
 [2.96781422e-09 9.97781836e-01 2.21816087e-03]]
344 [[0.61693747]
 [0.45201918]
 [0.50690346]]
344 [[2.73910173e-09 9.97899235e-01 2.10076240e-03]
 [2.93969047e-09 9.97781298e-01 2.21869938e-03]
 [3.16201093e-09 9.97658953e-01 2.34104359e-03]
 ...
 [4.40133097e-09 9.97051844e-01 2.94815180e-03]
 [1.32645776e-08 9.93477136e-01 6.52285043e-03]
 [2.95956099e-

366 [[0.61690544]
 [0.4520201 ]
 [0.5068377 ]]
366 [[2.58145811e-09 9.97889747e-01 2.11025010e-03]
 [2.77056349e-09 9.97779007e-01 2.22098977e-03]
 [2.98010283e-09 9.97659800e-01 2.34019669e-03]
 ...
 [4.14776901e-09 9.97040368e-01 2.95962784e-03]
 [1.24995143e-08 9.93495039e-01 6.50494833e-03]
 [2.78918681e-09 9.97770233e-01 2.22976433e-03]]
367 [[0.61690403]
 [0.45202014]
 [0.50683468]]
367 [[2.57473291e-09 9.97889329e-01 2.11066849e-03]
 [2.76334832e-09 9.97778906e-01 2.22109148e-03]
 [2.97234239e-09 9.97659836e-01 2.34016063e-03]
 ...
 [4.13695222e-09 9.97039863e-01 2.96013251e-03]
 [1.24668786e-08 9.93495830e-01 6.50415744e-03]
 [2.78191857e-09 9.97769744e-01 2.23025290e-03]]
368 [[0.61690263]
 [0.45202018]
 [0.50683165]]
368 [[2.56804354e-09 9.97888912e-01 2.11108581e-03]
 [2.75617158e-09 9.97778804e-01 2.22119298e-03]
 [2.96462328e-09 9.97659872e-01 2.34012478e-03]
 ...
 [4.12619309e-09 9.97039360e-01 2.96063577e-03]
 [1.24344169e-08 9.93496619e-01 6.50336846e-03]
 [2.77468906e-

390 [[0.61687261]
 [0.45202103]
 [0.50676473]]
390 [[2.42939058e-09 9.97879994e-01 2.12000396e-03]
 [2.60741526e-09 9.97776622e-01 2.22337509e-03]
 [2.80462480e-09 9.97660614e-01 2.33938270e-03]
 ...
 [3.90319192e-09 9.97028634e-01 2.97136234e-03]
 [1.17616208e-08 9.93513514e-01 6.48647431e-03]
 [2.62484162e-09 9.97758848e-01 2.24114986e-03]]
391 [[0.61687128]
 [0.45202106]
 [0.50676167]]
391 [[2.42345166e-09 9.97879600e-01 2.12039782e-03]
 [2.60104352e-09 9.97776525e-01 2.22347201e-03]
 [2.79777151e-09 9.97660646e-01 2.33935096e-03]
 ...
 [3.89364042e-09 9.97028161e-01 2.97183482e-03]
 [1.17328051e-08 9.93514262e-01 6.48572665e-03]
 [2.61842326e-09 9.97758388e-01 2.24160941e-03]]
392 [[0.61686996]
 [0.4520211 ]
 [0.50675861]]
392 [[2.41754244e-09 9.97879207e-01 2.12079071e-03]
 [2.59470364e-09 9.97776429e-01 2.22356874e-03]
 [2.79095249e-09 9.97660678e-01 2.33931938e-03]
 ...
 [3.88413672e-09 9.97027690e-01 2.97230603e-03]
 [1.17041335e-08 9.93515008e-01 6.48498068e-03]
 [2.61203700e-

415 [[0.61684047]
 [0.45202192]
 [0.50668823]]
415 [[2.28933857e-09 9.97870428e-01 2.12957011e-03]
 [2.45715486e-09 9.97774256e-01 2.22574134e-03]
 [2.64300814e-09 9.97661362e-01 2.33863495e-03]
 ...
 [3.67795470e-09 9.97017188e-01 2.98280819e-03]
 [1.10821314e-08 9.93531715e-01 6.46827346e-03]
 [2.47348448e-09 9.97747690e-01 2.25230763e-03]]
416 [[0.61683922]
 [0.45202196]
 [0.50668517]]
416 [[2.28407973e-09 9.97870057e-01 2.12994104e-03]
 [2.45151263e-09 9.97774164e-01 2.22583359e-03]
 [2.63693948e-09 9.97661390e-01 2.33860690e-03]
 ...
 [3.66949751e-09 9.97016746e-01 2.98325076e-03]
 [1.10566190e-08 9.93532423e-01 6.46756590e-03]
 [2.46780118e-09 9.97747257e-01 2.25274012e-03]]
417 [[0.61683798]
 [0.45202199]
 [0.50668211]]
417 [[2.27884560e-09 9.97869687e-01 2.13031111e-03]
 [2.44589692e-09 9.97774072e-01 2.22592566e-03]
 [2.63089934e-09 9.97661418e-01 2.33857899e-03]
 ...
 [3.66108008e-09 9.97016304e-01 2.98369219e-03]
 [1.10312267e-08 9.93533129e-01 6.46685985e-03]
 [2.46214460e-

439 [[0.61681136]
 [0.45202272]
 [0.50661496]]
439 [[2.16960959e-09 9.97861757e-01 2.13824065e-03]
 [2.32869622e-09 9.97772091e-01 2.22790654e-03]
 [2.50484060e-09 9.97662001e-01 2.33799662e-03]
 ...
 [3.48541366e-09 9.97006868e-01 2.99312848e-03]
 [1.05013232e-08 9.93548293e-01 6.45169643e-03]
 [2.34409280e-09 9.97737584e-01 2.26241370e-03]]
440 [[0.61681018]
 [0.45202275]
 [0.50661192]]
440 [[2.16489869e-09 9.97861406e-01 2.13859177e-03]
 [2.32364179e-09 9.97772003e-01 2.22799460e-03]
 [2.49940414e-09 9.97662026e-01 2.33797151e-03]
 ...
 [3.47783810e-09 9.97006451e-01 2.99354532e-03]
 [1.04784720e-08 9.93548966e-01 6.45102342e-03]
 [2.33900174e-09 9.97737175e-01 2.26282280e-03]]
441 [[0.616809  ]
 [0.45202278]
 [0.50660888]]
441 [[2.16020872e-09 9.97861056e-01 2.13894210e-03]
 [2.31860981e-09 9.97771915e-01 2.22808249e-03]
 [2.49399184e-09 9.97662051e-01 2.33794652e-03]
 ...
 [3.47029621e-09 9.97006035e-01 2.99396114e-03]
 [1.04557225e-08 9.93549638e-01 6.45035178e-03]
 [2.33393331e-

464 [[0.61678266]
 [0.45202349]
 [0.50653927]]
464 [[2.05780864e-09 9.97853208e-01 2.14679038e-03]
 [2.20874137e-09 9.97769939e-01 2.23005867e-03]
 [2.37581924e-09 9.97662597e-01 2.33740080e-03]
 ...
 [3.30563242e-09 9.96996742e-01 3.00325452e-03]
 [9.95904422e-09 9.93564722e-01 6.43526842e-03]
 [2.22327068e-09 9.97727625e-01 2.27237257e-03]]
465 [[0.61678155]
 [0.45202352]
 [0.50653626]]
465 [[2.05358163e-09 9.97852875e-01 2.14712280e-03]
 [2.20420603e-09 9.97769855e-01 2.23014267e-03]
 [2.37094110e-09 9.97662619e-01 2.33737827e-03]
 ...
 [3.29883539e-09 9.96996349e-01 3.00364722e-03]
 [9.93854292e-09 9.93565362e-01 6.43462794e-03]
 [2.21870263e-09 9.97727238e-01 2.27275966e-03]]
466 [[0.61678043]
 [0.45202355]
 [0.50653325]]
466 [[2.04937239e-09 9.97852543e-01 2.14745452e-03]
 [2.19968975e-09 9.97769771e-01 2.23022651e-03]
 [2.36608346e-09 9.97662642e-01 2.33735584e-03]
 ...
 [3.29206695e-09 9.96995958e-01 3.00403901e-03]
 [9.91812790e-09 9.93566001e-01 6.43398870e-03]
 [2.21415378e-

489 [[0.61675545]
 [0.45202421]
 [0.50646455]]
489 [[1.95721667e-09 9.97845104e-01 2.15489428e-03]
 [2.10081101e-09 9.97767885e-01 2.23211271e-03]
 [2.25973093e-09 9.97663133e-01 2.33686447e-03]
 ...
 [3.14388480e-09 9.96987191e-01 3.01280616e-03]
 [9.47119411e-09 9.93580374e-01 6.41961649e-03]
 [2.11456347e-09 9.97718191e-01 2.28180648e-03]]
490 [[0.61675439]
 [0.45202424]
 [0.50646158]]
490 [[1.95340217e-09 9.97844788e-01 2.15520975e-03]
 [2.09671819e-09 9.97767805e-01 2.23219293e-03]
 [2.25532876e-09 9.97663154e-01 2.33684412e-03]
 ...
 [3.13775141e-09 9.96986820e-01 3.01317708e-03]
 [9.45269574e-09 9.93580985e-01 6.41900553e-03]
 [2.11044126e-09 9.97717824e-01 2.28217362e-03]]
491 [[0.61675334]
 [0.45202427]
 [0.50645862]]
491 [[1.94960288e-09 9.97844473e-01 2.15552459e-03]
 [2.09264170e-09 9.97767725e-01 2.23227301e-03]
 [2.25094414e-09 9.97663174e-01 2.33682385e-03]
 ...
 [3.13164251e-09 9.96986450e-01 3.01354717e-03]
 [9.43427125e-09 9.93581595e-01 6.41839569e-03]
 [2.10633550e-

513 [[0.61673059]
 [0.45202486]
 [0.50639395]]
513 [[1.86969060e-09 9.97837706e-01 2.16229239e-03]
 [2.00689812e-09 9.97765999e-01 2.23399874e-03]
 [2.15871940e-09 9.97663601e-01 2.33639723e-03]
 ...
 [3.00315391e-09 9.96978511e-01 3.02148640e-03]
 [9.04676002e-09 9.93594735e-01 6.40525555e-03]
 [2.01997745e-09 9.97709584e-01 2.29041409e-03]]
514 [[0.61672958]
 [0.45202489]
 [0.50639103]]
514 [[1.86621744e-09 9.97837405e-01 2.16259302e-03]
 [2.00317149e-09 9.97765922e-01 2.23407558e-03]
 [2.15471108e-09 9.97663619e-01 2.33637867e-03]
 ...
 [2.99756964e-09 9.96978159e-01 3.02183833e-03]
 [9.02991883e-09 9.93595320e-01 6.40467048e-03]
 [2.01622416e-09 9.97709234e-01 2.29076378e-03]]
515 [[0.61672857]
 [0.45202491]
 [0.50638812]]
515 [[1.86275749e-09 9.97837105e-01 2.16289306e-03]
 [1.99945903e-09 9.97765846e-01 2.23415230e-03]
 [2.15071799e-09 9.97663638e-01 2.33636018e-03]
 ...
 [2.99200663e-09 9.96977807e-01 3.02218951e-03]
 [9.01314175e-09 9.93595905e-01 6.40408644e-03]
 [2.01248515e-

538 [[0.61670589]
 [0.4520255 ]
 [0.50632173]]
538 [[1.78665659e-09 9.97830363e-01 2.16963566e-03]
 [1.91780362e-09 9.97764118e-01 2.23588013e-03]
 [2.06289026e-09 9.97664045e-01 2.33595312e-03]
 ...
 [2.86965225e-09 9.96969932e-01 3.03006492e-03]
 [8.64415301e-09 9.93609061e-01 6.39093010e-03]
 [1.93024690e-09 9.97701044e-01 2.29895360e-03]]
539 [[0.61670493]
 [0.45202552]
 [0.50631887]]
539 [[1.78349215e-09 9.97830076e-01 2.16992213e-03]
 [1.91440819e-09 9.97764044e-01 2.23595370e-03]
 [2.05923816e-09 9.97664062e-01 2.33593618e-03]
 ...
 [2.86456461e-09 9.96969598e-01 3.03039883e-03]
 [8.62881047e-09 9.93609622e-01 6.39036978e-03]
 [1.92682727e-09 9.97700711e-01 2.29928665e-03]]
540 [[0.61670396]
 [0.45202555]
 [0.50631602]]
540 [[1.78033919e-09 9.97829790e-01 2.17020806e-03]
 [1.91102507e-09 9.97763971e-01 2.23602715e-03]
 [2.05559930e-09 9.97664079e-01 2.33591929e-03]
 ...
 [2.85949543e-09 9.96969265e-01 3.03073205e-03]
 [8.61352363e-09 9.93610181e-01 6.38981040e-03]
 [1.92342005e-

562 [[0.61668321]
 [0.45202608]
 [0.50625377]]
562 [[1.71375477e-09 9.97823633e-01 2.17636533e-03]
 [1.83957963e-09 9.97762386e-01 2.23761179e-03]
 [1.97875315e-09 9.97664436e-01 2.33556224e-03]
 ...
 [2.75244658e-09 9.96962103e-01 3.03789388e-03]
 [8.29071082e-09 9.93622254e-01 6.37773757e-03]
 [1.85146658e-09 9.97693222e-01 2.30677587e-03]]
563 [[0.61668229]
 [0.4520261 ]
 [0.50625097]]
563 [[1.71084928e-09 9.97823359e-01 2.17663932e-03]
 [1.83646200e-09 9.97762316e-01 2.23768243e-03]
 [1.97539986e-09 9.97664451e-01 2.33554664e-03]
 ...
 [2.74777549e-09 9.96961785e-01 3.03821195e-03]
 [8.27662520e-09 9.93622793e-01 6.37719914e-03]
 [1.84832683e-09 9.97692904e-01 2.30709426e-03]]
564 [[0.61668137]
 [0.45202612]
 [0.50624817]]
564 [[1.70795389e-09 9.97823085e-01 2.17691280e-03]
 [1.83335520e-09 9.97762245e-01 2.23775296e-03]
 [1.97205821e-09 9.97664467e-01 2.33553109e-03]
 ...
 [2.74312062e-09 9.96961468e-01 3.03852939e-03]
 [8.26258854e-09 9.93623330e-01 6.37666159e-03]
 [1.84519798e-

586 [[0.61666147]
 [0.45202662]
 [0.5061872 ]]
586 [[1.64670387e-09 9.97817192e-01 2.18280657e-03]
 [1.76763265e-09 9.97760723e-01 2.23927536e-03]
 [1.90136741e-09 9.97664796e-01 2.33520167e-03]
 ...
 [2.64465229e-09 9.96954639e-01 3.04535790e-03]
 [7.96566663e-09 9.93634940e-01 6.36505159e-03]
 [1.77900976e-09 9.97685739e-01 2.31425965e-03]]
587 [[0.61666059]
 [0.45202665]
 [0.50618446]]
587 [[1.64402659e-09 9.97816929e-01 2.18306903e-03]
 [1.76475985e-09 9.97760655e-01 2.23934327e-03]
 [1.89827745e-09 9.97664811e-01 2.33518725e-03]
 ...
 [2.64034826e-09 9.96954336e-01 3.04566142e-03]
 [7.95268857e-09 9.93635459e-01 6.36453344e-03]
 [1.77611664e-09 9.97685434e-01 2.31456452e-03]]
588 [[0.6166597 ]
 [0.45202667]
 [0.50618172]]
588 [[1.64135823e-09 9.97816667e-01 2.18333103e-03]
 [1.76189662e-09 9.97760587e-01 2.23941106e-03]
 [1.89519777e-09 9.97664825e-01 2.33517287e-03]
 ...
 [2.63605857e-09 9.96954033e-01 3.04596436e-03]
 [7.93975377e-09 9.93635976e-01 6.36401611e-03]
 [1.77323316e-

610 [[0.61664059]
 [0.45202714]
 [0.50612205]]
610 [[1.58482187e-09 9.97811017e-01 2.18898121e-03]
 [1.70123107e-09 9.97759123e-01 2.24087526e-03]
 [1.82994615e-09 9.97665130e-01 2.33486777e-03]
 ...
 [2.54517195e-09 9.96947511e-01 3.05248597e-03]
 [7.66570771e-09 9.93647157e-01 6.35283552e-03]
 [1.71213926e-09 9.97678568e-01 2.32143075e-03]]
611 [[0.61663974]
 [0.45202716]
 [0.50611937]]
611 [[1.58234675e-09 9.97810765e-01 2.18923300e-03]
 [1.69857516e-09 9.97759058e-01 2.24094060e-03]
 [1.82708945e-09 9.97665144e-01 2.33485439e-03]
 ...
 [2.54119308e-09 9.96947221e-01 3.05277608e-03]
 [7.65371068e-09 9.93647656e-01 6.35233622e-03]
 [1.70946463e-09 9.97678275e-01 2.32172311e-03]]
612 [[0.61663889]
 [0.45202718]
 [0.50611669]]
612 [[1.57987954e-09 9.97810514e-01 2.18948436e-03]
 [1.69592774e-09 9.97758992e-01 2.24100584e-03]
 [1.82424189e-09 9.97665157e-01 2.33484105e-03]
 ...
 [2.53722693e-09 9.96946932e-01 3.05306564e-03]
 [7.64175206e-09 9.93648155e-01 6.35183768e-03]
 [1.70679855e-

634 [[0.6166205 ]
 [0.45202764]
 [0.50605833]]
634 [[1.52752914e-09 9.97805090e-01 2.19490877e-03]
 [1.63975311e-09 9.97757583e-01 2.24241554e-03]
 [1.76382058e-09 9.97665441e-01 2.33455745e-03]
 ...
 [2.45307294e-09 9.96940694e-01 3.05930392e-03]
 [7.38801887e-09 9.93658936e-01 6.34105670e-03]
 [1.65022860e-09 9.97671686e-01 2.32831226e-03]]
635 [[0.61661968]
 [0.45202766]
 [0.50605571]]
635 [[1.52523395e-09 9.97804848e-01 2.19515065e-03]
 [1.63729024e-09 9.97757520e-01 2.24247848e-03]
 [1.76117152e-09 9.97665453e-01 2.33454499e-03]
 ...
 [2.44938346e-09 9.96940416e-01 3.05958162e-03]
 [7.37689495e-09 9.93659418e-01 6.34057496e-03]
 [1.64774842e-09 9.97671405e-01 2.32859302e-03]]
636 [[0.61661886]
 [0.45202768]
 [0.50605309]]
636 [[1.52294582e-09 9.97804606e-01 2.19539214e-03]
 [1.63483495e-09 9.97757457e-01 2.24254132e-03]
 [1.75853061e-09 9.97665466e-01 2.33453257e-03]
 ...
 [2.44570534e-09 9.96940139e-01 3.05985882e-03]
 [7.36580531e-09 9.93659899e-01 6.34009393e-03]
 [1.64527588e-

658 [[0.61660115]
 [0.45202811]
 [0.50599604]]
658 [[1.47432985e-09 9.97799392e-01 2.20060675e-03]
 [1.58266688e-09 9.97756099e-01 2.24389991e-03]
 [1.70241865e-09 9.97665730e-01 2.33426810e-03]
 ...
 [2.36755751e-09 9.96934163e-01 3.06583480e-03]
 [7.13019227e-09 9.93670307e-01 6.32968582e-03]
 [1.59274186e-09 9.97665074e-01 2.33492484e-03]]
659 [[0.61660036]
 [0.45202813]
 [0.50599347]]
659 [[1.47219553e-09 9.97799159e-01 2.20083942e-03]
 [1.58037660e-09 9.97756038e-01 2.24396059e-03]
 [1.69995523e-09 9.97665742e-01 2.33425647e-03]
 ...
 [2.36412675e-09 9.96933897e-01 3.06610100e-03]
 [7.11984888e-09 9.93670772e-01 6.32922049e-03]
 [1.59043554e-09 9.97664804e-01 2.33519481e-03]]
660 [[0.61659957]
 [0.45202814]
 [0.50599091]]
660 [[1.47006754e-09 9.97798927e-01 2.20107173e-03]
 [1.57809311e-09 9.97755977e-01 2.24402119e-03]
 [1.69749911e-09 9.97665753e-01 2.33424486e-03]
 ...
 [2.36070617e-09 9.96933631e-01 3.06636675e-03]
 [7.10953619e-09 9.93671237e-01 6.32875582e-03]
 [1.58813606e-

682 [[0.61658248]
 [0.45202856]
 [0.50593515]]
682 [[1.42479737e-09 9.97793908e-01 2.20609093e-03]
 [1.52951471e-09 9.97754667e-01 2.24533179e-03]
 [1.64524810e-09 9.97666001e-01 2.33399749e-03]
 ...
 [2.28793926e-09 9.96927898e-01 3.07209931e-03]
 [6.89015620e-09 9.93681297e-01 6.31869651e-03]
 [1.53921794e-09 9.97658711e-01 2.34128710e-03]]
683 [[0.61658171]
 [0.45202857]
 [0.50593264]]
683 [[1.42280746e-09 9.97793684e-01 2.20631501e-03]
 [1.52737936e-09 9.97754608e-01 2.24539036e-03]
 [1.64295132e-09 9.97666012e-01 2.33398659e-03]
 ...
 [2.28474074e-09 9.96927643e-01 3.07235484e-03]
 [6.88051342e-09 9.93681747e-01 6.31824654e-03]
 [1.53706769e-09 9.97658451e-01 2.34154701e-03]]
684 [[0.61658095]
 [0.45202859]
 [0.50593014]]
684 [[1.42082324e-09 9.97793460e-01 2.20653875e-03]
 [1.52525013e-09 9.97754550e-01 2.24544884e-03]
 [1.64066111e-09 9.97666023e-01 2.33397572e-03]
 ...
 [2.28155139e-09 9.96927388e-01 3.07260993e-03]
 [6.87089827e-09 9.93682196e-01 6.31779719e-03]
 [1.53492358e-

706 [[0.61656444]
 [0.45202898]
 [0.50587565]]
706 [[1.37856255e-09 9.97788623e-01 2.21137553e-03]
 [1.47990058e-09 9.97753284e-01 2.24671431e-03]
 [1.59188299e-09 9.97666255e-01 2.33374367e-03]
 ...
 [2.21362430e-09 9.96921882e-01 3.07811608e-03]
 [6.66611830e-09 9.93691928e-01 6.30806491e-03]
 [1.48925785e-09 9.97652583e-01 2.34741582e-03]]
707 [[0.6165637]
 [0.452029 ]
 [0.5058732]]
707 [[1.37670277e-09 9.97788407e-01 2.21159158e-03]
 [1.47790485e-09 9.97753228e-01 2.24677089e-03]
 [1.58973638e-09 9.97666265e-01 2.33373344e-03]
 ...
 [2.21063506e-09 9.96921636e-01 3.07836166e-03]
 [6.65710681e-09 9.93692364e-01 6.30762936e-03]
 [1.48724823e-09 9.97652332e-01 2.34766634e-03]]
708 [[0.61656297]
 [0.45202902]
 [0.50587075]]
708 [[1.37484813e-09 9.97788191e-01 2.21180732e-03]
 [1.47591464e-09 9.97753171e-01 2.24682738e-03]
 [1.58759570e-09 9.97666275e-01 2.33372323e-03]
 ...
 [2.20765409e-09 9.96921391e-01 3.07860684e-03]
 [6.64812025e-09 9.93692799e-01 6.30719439e-03]
 [1.48524416e-09 

730 [[0.616547  ]
 [0.45202939]
 [0.50581751]]
730 [[1.33530435e-09 9.97783525e-01 2.21647346e-03]
 [1.43348009e-09 9.97751948e-01 2.24805037e-03]
 [1.54195289e-09 9.97666493e-01 2.33350500e-03]
 ...
 [2.14409618e-09 9.96916096e-01 3.08390192e-03]
 [6.45651990e-09 9.93702224e-01 6.29776938e-03]
 [1.44251461e-09 9.97646672e-01 2.35332619e-03]]
731 [[0.61654628]
 [0.45202941]
 [0.50581512]]
731 [[1.33356225e-09 9.97783317e-01 2.21668200e-03]
 [1.43161062e-09 9.97751894e-01 2.24810507e-03]
 [1.53994208e-09 9.97666503e-01 2.33349536e-03]
 ...
 [2.14129618e-09 9.96915860e-01 3.08413821e-03]
 [6.44807925e-09 9.93702646e-01 6.29734740e-03]
 [1.44063217e-09 9.97646431e-01 2.35356793e-03]]
732 [[0.61654557]
 [0.45202943]
 [0.50581273]]
732 [[1.33182481e-09 9.97783108e-01 2.21689024e-03]
 [1.42974615e-09 9.97751839e-01 2.24815969e-03]
 [1.53793665e-09 9.97666513e-01 2.33348575e-03]
 ...
 [2.13850367e-09 9.96915624e-01 3.08437413e-03]
 [6.43966119e-09 9.93703068e-01 6.29692596e-03]
 [1.43875476e-

754 [[0.61653011]
 [0.45202979]
 [0.5057607 ]]
754 [[1.29474224e-09 9.97778602e-01 2.22139644e-03]
 [1.38995228e-09 9.97750656e-01 2.24934262e-03]
 [1.49513410e-09 9.97666718e-01 2.33328001e-03]
 ...
 [2.07890359e-09 9.96910526e-01 3.08947204e-03]
 [6.25999911e-09 9.93712204e-01 6.28779022e-03]
 [1.39868502e-09 9.97640967e-01 2.35903203e-03]]
755 [[0.61652942]
 [0.4520298 ]
 [0.50575836]]
755 [[1.29310691e-09 9.97778401e-01 2.22159793e-03]
 [1.38819737e-09 9.97750603e-01 2.24939555e-03]
 [1.49324652e-09 9.97666728e-01 2.33327091e-03]
 ...
 [2.07627529e-09 9.96910298e-01 3.08969966e-03]
 [6.25207636e-09 9.93712613e-01 6.28738101e-03]
 [1.39691797e-09 9.97640733e-01 2.35926553e-03]]
756 [[0.61652873]
 [0.45202982]
 [0.50575602]]
756 [[1.29147582e-09 9.97778200e-01 2.22179913e-03]
 [1.38644701e-09 9.97750550e-01 2.24944841e-03]
 [1.49136381e-09 9.97666737e-01 2.33326184e-03]
 ...
 [2.07365380e-09 9.96910071e-01 3.08992693e-03]
 [6.24417413e-09 9.93713021e-01 6.28697233e-03]
 [1.39515549e-

778 [[0.61651374]
 [0.45203017]
 [0.50570518]]
778 [[1.25662997e-09 9.97773844e-01 2.22615515e-03]
 [1.34905299e-09 9.97749405e-01 2.25059352e-03]
 [1.45114250e-09 9.97666931e-01 2.33306743e-03]
 ...
 [2.01765042e-09 9.96905158e-01 3.09484029e-03]
 [6.07536061e-09 9.93721885e-01 6.27810942e-03]
 [1.35750295e-09 9.97635453e-01 2.36454590e-03]]
779 [[0.61651307]
 [0.45203018]
 [0.50570289]]
779 [[1.25509183e-09 9.97773649e-01 2.22635001e-03]
 [1.34740235e-09 9.97749354e-01 2.25064477e-03]
 [1.44936706e-09 9.97666940e-01 2.33305883e-03]
 ...
 [2.01517839e-09 9.96904938e-01 3.09505978e-03]
 [6.06790918e-09 9.93722282e-01 6.27771228e-03]
 [1.35584092e-09 9.97635227e-01 2.36477165e-03]]
780 [[0.6165124 ]
 [0.4520302 ]
 [0.50570061]]
780 [[1.25355754e-09 9.97773454e-01 2.22654460e-03]
 [1.34575586e-09 9.97749303e-01 2.25069596e-03]
 [1.44759608e-09 9.97666948e-01 2.33305024e-03]
 ...
 [2.01271256e-09 9.96904719e-01 3.09527893e-03]
 [6.06047647e-09 9.93722678e-01 6.27731563e-03]
 [1.35418306e-

802 [[0.61649786]
 [0.45203053]
 [0.50565092]]
802 [[1.22075051e-09 9.97769239e-01 2.23075934e-03]
 [1.31054937e-09 9.97748193e-01 2.25180533e-03]
 [1.40972765e-09 9.97667132e-01 2.33286616e-03]
 ...
 [1.95998756e-09 9.96899979e-01 3.10001925e-03]
 [5.90155093e-09 9.93731284e-01 6.26871049e-03]
 [1.31873382e-09 9.97630119e-01 2.36987927e-03]]
803 [[0.61649721]
 [0.45203054]
 [0.50564868]]
803 [[1.21930107e-09 9.97769051e-01 2.23094796e-03]
 [1.30899391e-09 9.97748144e-01 2.25185501e-03]
 [1.40805458e-09 9.97667141e-01 2.33285801e-03]
 ...
 [1.95765816e-09 9.96899767e-01 3.10023110e-03]
 [5.89452970e-09 9.93731669e-01 6.26832475e-03]
 [1.31716766e-09 9.97629901e-01 2.37009774e-03]]
804 [[0.61649656]
 [0.45203056]
 [0.50564645]]
804 [[1.21785516e-09 9.97768862e-01 2.23113633e-03]
 [1.30744224e-09 9.97748094e-01 2.25190462e-03]
 [1.40638559e-09 9.97667149e-01 2.33284987e-03]
 ...
 [1.95533443e-09 9.96899555e-01 3.10044265e-03]
 [5.88752558e-09 9.93732055e-01 6.26793948e-03]
 [1.31560530e-

826 [[0.61648244]
 [0.45203088]
 [0.50559788]]
826 [[1.18691181e-09 9.97764781e-01 2.23521795e-03]
 [1.27423539e-09 9.97747019e-01 2.25298016e-03]
 [1.37066794e-09 9.97667323e-01 2.33267521e-03]
 ...
 [1.90560609e-09 9.96894978e-01 3.10502042e-03]
 [5.73763797e-09 9.93740416e-01 6.25957828e-03]
 [1.28217009e-09 9.97624956e-01 2.37504265e-03]]
827 [[0.6164818 ]
 [0.45203089]
 [0.5055957 ]]
827 [[1.18554356e-09 9.97764598e-01 2.23540069e-03]
 [1.27276705e-09 9.97746970e-01 2.25302834e-03]
 [1.36908858e-09 9.97667331e-01 2.33266747e-03]
 ...
 [1.90340724e-09 9.96894773e-01 3.10522510e-03]
 [5.73101047e-09 9.93740791e-01 6.25920335e-03]
 [1.28069166e-09 9.97624744e-01 2.37525425e-03]]
828 [[0.61648117]
 [0.45203091]
 [0.50559351]]
828 [[1.18417854e-09 9.97764416e-01 2.23558319e-03]
 [1.27130218e-09 9.97746922e-01 2.25307645e-03]
 [1.36751294e-09 9.97667339e-01 2.33265974e-03]
 ...
 [1.90121359e-09 9.96894569e-01 3.10542949e-03]
 [5.72439865e-09 9.93741165e-01 6.25882885e-03]
 [1.27921673e-

851 [[0.61646683]
 [0.45203123]
 [0.50554389]]
851 [[1.15364956e-09 9.97760282e-01 2.23971637e-03]
 [1.23853968e-09 9.97745832e-01 2.25416670e-03]
 [1.33227319e-09 9.97667512e-01 2.33248634e-03]
 ...
 [1.85215261e-09 9.96889946e-01 3.11005224e-03]
 [5.57652775e-09 9.93749660e-01 6.25033415e-03]
 [1.24622950e-09 9.97619748e-01 2.38025078e-03]]
852 [[0.61646622]
 [0.45203124]
 [0.50554176]]
852 [[1.15235879e-09 9.97760106e-01 2.23989333e-03]
 [1.23715447e-09 9.97745785e-01 2.25421340e-03]
 [1.33078324e-09 9.97667520e-01 2.33247899e-03]
 ...
 [1.85007834e-09 9.96889748e-01 3.11024989e-03]
 [5.57027594e-09 9.93750025e-01 6.24996988e-03]
 [1.24483480e-09 9.97619543e-01 2.38045563e-03]]
853 [[0.61646561]
 [0.45203126]
 [0.50553963]]
853 [[1.15107098e-09 9.97759929e-01 2.24007006e-03]
 [1.23577243e-09 9.97745739e-01 2.25426004e-03]
 [1.32929670e-09 9.97667527e-01 2.33247165e-03]
 ...
 [1.84800882e-09 9.96889551e-01 3.11044727e-03]
 [5.56403848e-09 9.93750388e-01 6.24960602e-03]
 [1.24344330e-

875 [[0.61645227]
 [0.45203155]
 [0.50549324]]
875 [[1.12346779e-09 9.97756096e-01 2.24390252e-03]
 [1.20614948e-09 9.97744727e-01 2.25527189e-03]
 [1.29743384e-09 9.97667685e-01 2.33231387e-03]
 ...
 [1.80365095e-09 9.96885276e-01 3.11472214e-03]
 [5.43034736e-09 9.93758290e-01 6.24170432e-03]
 [1.21361766e-09 9.97614903e-01 2.38509618e-03]]
876 [[0.61645167]
 [0.45203157]
 [0.50549115]]
876 [[1.12224532e-09 9.97755925e-01 2.24407423e-03]
 [1.20483756e-09 9.97744682e-01 2.25531724e-03]
 [1.29602272e-09 9.97667692e-01 2.33230686e-03]
 ...
 [1.80168649e-09 9.96885085e-01 3.11491344e-03]
 [5.42442673e-09 9.93758645e-01 6.24134976e-03]
 [1.21229677e-09 9.97614704e-01 2.38529491e-03]]
877 [[0.61645108]
 [0.45203158]
 [0.50548906]]
877 [[1.12102558e-09 9.97755753e-01 2.24424574e-03]
 [1.20352856e-09 9.97744636e-01 2.25536254e-03]
 [1.29461475e-09 9.97667699e-01 2.33229986e-03]
 ...
 [1.79972642e-09 9.96884894e-01 3.11510448e-03]
 [5.41851933e-09 9.93758999e-01 6.24099559e-03]
 [1.21097883e-

900 [[0.61643752]
 [0.45203188]
 [0.50544165]]
900 [[1.09370347e-09 9.97751866e-01 2.24813282e-03]
 [1.17420697e-09 9.97743609e-01 2.25638966e-03]
 [1.26307600e-09 9.97667856e-01 2.33214266e-03]
 ...
 [1.75582146e-09 9.96880569e-01 3.11942894e-03]
 [5.28619757e-09 9.93767038e-01 6.23295665e-03]
 [1.18145710e-09 9.97610007e-01 2.38999151e-03]]
901 [[0.61643693]
 [0.45203189]
 [0.50543961]]
901 [[1.09254650e-09 9.97751700e-01 2.24829937e-03]
 [1.17296533e-09 9.97743565e-01 2.25643368e-03]
 [1.26174047e-09 9.97667863e-01 2.33213598e-03]
 ...
 [1.75396231e-09 9.96880384e-01 3.11961400e-03]
 [5.28059451e-09 9.93767383e-01 6.23261170e-03]
 [1.18020700e-09 9.97609815e-01 2.39018422e-03]]
902 [[0.61643635]
 [0.4520319 ]
 [0.50543757]]
902 [[1.09139204e-09 9.97751533e-01 2.24846572e-03]
 [1.17172638e-09 9.97743521e-01 2.25647765e-03]
 [1.26040783e-09 9.97667869e-01 2.33212931e-03]
 ...
 [1.75210720e-09 9.96880199e-01 3.11979881e-03]
 [5.27500361e-09 9.93767728e-01 6.23226712e-03]
 [1.17895960e-

924 [[0.61642372]
 [0.45203218]
 [0.50539323]]
924 [[1.06661242e-09 9.97747923e-01 2.25207547e-03]
 [1.14513309e-09 9.97742567e-01 2.25743218e-03]
 [1.23180365e-09 9.97668013e-01 2.33198579e-03]
 ...
 [1.71228895e-09 9.96876194e-01 3.12380452e-03]
 [5.15500226e-09 9.93775215e-01 6.22477957e-03]
 [1.15218524e-09 9.97605446e-01 2.39455293e-03]]
925 [[0.61642316]
 [0.45203219]
 [0.50539123]]
925 [[1.06551347e-09 9.97747762e-01 2.25223732e-03]
 [1.14395370e-09 9.97742524e-01 2.25747499e-03]
 [1.23053508e-09 9.97668019e-01 2.33197940e-03]
 ...
 [1.71052307e-09 9.96876014e-01 3.12398391e-03]
 [5.14968045e-09 9.93775551e-01 6.22444340e-03]
 [1.15099783e-09 9.97605259e-01 2.39474016e-03]]
926 [[0.61642259]
 [0.4520322 ]
 [0.50538924]]
926 [[1.06441684e-09 9.97747600e-01 2.25239898e-03]
 [1.14277680e-09 9.97742481e-01 2.25751775e-03]
 [1.22926918e-09 9.97668026e-01 2.33197303e-03]
 ...
 [1.70876092e-09 9.96875835e-01 3.12416307e-03]
 [5.14436990e-09 9.93775887e-01 6.22410758e-03]
 [1.14981292e-

948 [[0.61641028]
 [0.45203247]
 [0.50534585]]
948 [[1.04086349e-09 9.97744091e-01 2.25590809e-03]
 [1.11749931e-09 9.97741553e-01 2.25844626e-03]
 [1.20208027e-09 9.97668163e-01 2.33183569e-03]
 ...
 [1.67091414e-09 9.96871951e-01 3.12804766e-03]
 [5.03031345e-09 9.93783187e-01 6.21680832e-03]
 [1.12436371e-09 9.97601013e-01 2.39898609e-03]]
949 [[0.61640972]
 [0.45203248]
 [0.50534389]]
949 [[1.03981826e-09 9.97743933e-01 2.25606548e-03]
 [1.11637757e-09 9.97741511e-01 2.25848792e-03]
 [1.20087370e-09 9.97668169e-01 2.33182957e-03]
 ...
 [1.66923463e-09 9.96871777e-01 3.12822168e-03]
 [5.02525209e-09 9.93783514e-01 6.21648051e-03]
 [1.12323435e-09 9.97600831e-01 2.39916812e-03]]
950 [[0.61640917]
 [0.45203249]
 [0.50534194]]
950 [[1.03877519e-09 9.97743776e-01 2.25622268e-03]
 [1.11525813e-09 9.97741469e-01 2.25852953e-03]
 [1.19966961e-09 9.97668175e-01 2.33182347e-03]
 ...
 [1.66755858e-09 9.96871603e-01 3.12839549e-03]
 [5.02020115e-09 9.93783842e-01 6.21615304e-03]
 [1.12210732e-

972 [[0.61639716]
 [0.45203275]
 [0.50529947]]
972 [[1.01635862e-09 9.97740363e-01 2.25963617e-03]
 [1.09120042e-09 9.97740566e-01 2.25943324e-03]
 [1.17379268e-09 9.97668307e-01 2.33169187e-03]
 ...
 [1.63153933e-09 9.96867833e-01 3.13216529e-03]
 [4.91165537e-09 9.93790962e-01 6.20903340e-03]
 [1.09788653e-09 9.97596701e-01 2.40329742e-03]]
973 [[0.61639662]
 [0.45203276]
 [0.50529756]]
973 [[1.01536324e-09 9.97740210e-01 2.25978931e-03]
 [1.09013217e-09 9.97740525e-01 2.25947380e-03]
 [1.17264364e-09 9.97668313e-01 2.33168601e-03]
 ...
 [1.62993996e-09 9.96867664e-01 3.13233423e-03]
 [4.90683566e-09 9.93791282e-01 6.20871357e-03]
 [1.09681104e-09 9.97596524e-01 2.40347451e-03]]
974 [[0.61639608]
 [0.45203278]
 [0.50529565]]
974 [[1.01436986e-09 9.97740057e-01 2.25994229e-03]
 [1.08906605e-09 9.97740485e-01 2.25951431e-03]
 [1.17149691e-09 9.97668319e-01 2.33168015e-03]
 ...
 [1.62834380e-09 9.96867495e-01 3.13250297e-03]
 [4.90202563e-09 9.93791601e-01 6.20839407e-03]
 [1.09573771e-

996 [[0.61638436]
 [0.45203303]
 [0.50525407]]
996 [[9.93009091e-10 9.97736734e-01 2.26326480e-03]
 [1.06614125e-09 9.97739605e-01 2.26039438e-03]
 [1.14683852e-09 9.97668445e-01 2.33155389e-03]
 ...
 [1.59402187e-09 9.96863835e-01 3.13616384e-03]
 [4.79859772e-09 9.93798549e-01 6.20144595e-03]
 [1.07265785e-09 9.97592506e-01 2.40749290e-03]]
997 [[0.61638383]
 [0.45203304]
 [0.5052522 ]]
997 [[9.92060052e-10 9.97736585e-01 2.26341390e-03]
 [1.06512272e-09 9.97739565e-01 2.26043389e-03]
 [1.14574296e-09 9.97668451e-01 2.33154826e-03]
 ...
 [1.59249699e-09 9.96863670e-01 3.13632796e-03]
 [4.79400263e-09 9.93798861e-01 6.20113375e-03]
 [1.07163244e-09 9.97592334e-01 2.40766528e-03]]
998 [[0.6163833 ]
 [0.45203305]
 [0.50525033]]
998 [[9.91112872e-10 9.97736436e-01 2.26356284e-03]
 [1.06410618e-09 9.97739526e-01 2.26047335e-03]
 [1.14464955e-09 9.97668456e-01 2.33154264e-03]
 ...
 [1.59097511e-09 9.96863507e-01 3.13649187e-03]
 [4.78941655e-09 9.93799173e-01 6.20082186e-03]
 [1.07060903e-

In [481]:
mean=ugmm.m

In [482]:
mean

array([[0.61638225],
       [0.45203307],
       [0.50524659]])